# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    app.html_parser:
        class: AppBundle\Utils\HtmlParser
        arguments: ["%parse_url%"]
